---
- name: Install dhcp packages
  package:
    name: "{{ dhcp_packages }}"
    state: present
  become: yes

- name: "Apply SELINUX directives"
  shell: "{{ item }}"
  loop:
    - "ausearch -c 'dhcpd' --raw | audit2allow -M my-dhcpd"
    - "semodule -X 300 -i my-dhcpd.pp"
  when: "(ansible_selinux is defined) and (ansible_selinux.status == 'enabled') and (ansible_selinux.mode == 'enforcing' or ansible_selinux.config_mode == 'enforcing')"
  
- name: Apply template
  template:
    src: "templates/dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: Restart dhcpd
...
